- .idea/misc.xml
- .idea/workspace.xml
- src/main/java/com/umbrella/domain/Comment/CommentRepository.java
* CommentRepository  생성 
* CommentRepository extends JpaRepository<Comment, Long>
> <FEAT> : Create CommentRepository

- .idea/workspace.xml
- src/main/java/com/umbrella/domain/Comment/Comment.java
> [FEAT, REFACTOR] : update Comment Entity

- .gitignore
ignore 추가
idea  파일 충돌로 인한 git ignore 파일추가 
Intellij + all file 추가
ignore 파일  .idea  -> main root 로 이동
> [FEAT] Add a Git ignore

- src/main/java/com/umbrella/controller/PostController.java
- src/main/java/com/umbrella/domain/exception/CommentException.java
- src/main/java/com/umbrella/domain/exception/CommentExceptionType.java
- src/main/java/com/umbrella/domain/exception/PostException.java
- src/main/java/com/umbrella/domain/exception/PostExceptionType.java
- src/main/java/com/umbrella/domain/exception/UserException.java
- src/main/java/com/umbrella/domain/exception/UserExceptionType.java
- src/main/java/com/umbrella/exception/BaseException.java
- src/main/java/com/umbrella/exception/ExceptionAdvice.java
- src/main/java/com/umbrella/exception/ExceptionDto.java
- src/main/java/com/umbrella/exception/GlobalException.java
- src/main/java/com/umbrella/exception/GlobalExceptionType.java
- src/main/java/com/umbrella/service/Impl/PostServiceImpl.java
Add a Exception Code
create a Exception Class
Use a Security Utils Dependency, Injection in PostService
Add in Exception file, @RestControllerAdvice , @ExceptionHandler
Add in domain file, exception folder, Comment,User,Post Exception class and individual Type enum class
ETC: RestController Exception 처리를 위한 ExceptionDto 공통 dto를 추가함
Add a BaseExceptionType, BaseException, Post,User,Comment ExceptionType class and individual Exception class
> [FEAT] Add a Exception Code 

- src/main/java/com/umbrella/domain/exception/CommentExceptionType.java
- src/main/java/com/umbrella/dto/comment/CommentRequestDto.java
- src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
- src/main/java/com/umbrella/service/Impl/PostServiceImpl.java
* Comment Service Validation Logic Update
> [FEAT, REFACTOR] CommentService Validation Logic update

- src/main/java/com/umbrella/controller/CommentController.java
- src/main/java/com/umbrella/dto/comment/CommentPageRequestDto.java
- src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
* Comment Service 컨트롤러 제작했습니다.
* 기존에 요청 DTO가 CommentRequest 하나만 있었는데 int pageNumber 이라는 변수에 @NotNull Validation을 적용하려고 CommentPageRequestDto를 추가적으로 제작했습니다.
> [FEAT] Comment Service edit Controller

- src/main/java/com/umbrella/controller/PostHeartController.java
- src/main/java/com/umbrella/domain/Heart/PostHeart.java
- src/main/java/com/umbrella/domain/Heart/PostHeartRepository.java
- src/main/java/com/umbrella/domain/Post/Post.java
- src/main/java/com/umbrella/domain/exception/PostExceptionType.java
- src/main/java/com/umbrella/dto/Heart/HeartRequestDto.java
- src/main/java/com/umbrella/service/HeartService.java
- src/main/java/com/umbrella/service/Impl/HeartServiceImpl.java
Add a Heart function
Add a PostHeartEntity, PostHeartService, HeartServiceImpl, HeartRequestDto,
> [FEAT] Add a Heart function

- src/main/java/com/umbrella/dto/Heart/HeartRequestDto.java
Add a HeartRequestDto postId field
Add a HeartRequestDto postId field
Add a HeartRequestDto postId field
> [FEAT]Add a HeartRequestDto postId field

- src/test/java/com/umbrella/project_umbrella/jwt/JwtServiceTest.java
- src/test/java/com/umbrella/project_umbrella/service/UserServiceTest.java
기존에는 사용하지 못하는 TEST 들을 주석 처리 해뒀는데 미관상 안좋아보여서 @Disabled 를 붙임
> [REFACTOR] 사용하지 않는 TEST Method 에 @Disabeld 추가

- src/main/java/com/umbrella/controller/UserController.java
- src/main/java/com/umbrella/domain/User/User.java
- src/main/java/com/umbrella/dto/user/UserInfoDto.java
- src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
- src/main/java/com/umbrella/dto/user/UserUpdateDto.java
- src/main/java/com/umbrella/dto/user/WithdrawUserDto.java
- src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
- src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
- src/test/java/com/umbrella/project_umbrella/controller/UserControllerTest.java
Note: further occurrences of this error will be logged at DEBUG level. 에러가 발생하여 GET -> POST 로 변경함
그에 따른 TEST 코드 수정
그 외의 변경점들은 사용하지 않는 import 삭제 및 사용하지 않는 어노테이션들 삭제
추가적으로 Controller 의 모든 기능 POSTMAN 으로 성공적으로 수행시켰음
> [FIX] UserController 의  getInfo 수행 시 에러가 발생하여 Http Method 를 변경함

- src/main/java/com/umbrella/exception/ExceptionAdvice.java
if else-if 문을 반복해서 쓰는 것보다는 switch 문을 사용하는게 더 보기 좋을 것 같아서 고쳤음
> [REFACTOR] ExceptionAdvice 관련 리팩토링

- src/main/java/com/umbrella/Config/SocketConfig/WebSocketMessageBrokerConfig.java
- src/main/java/com/umbrella/controller/ChatController.java
- src/main/java/com/umbrella/controller/ChatRoomController.java
- src/main/java/com/umbrella/domain/Chat/ChatMessage.java
- src/main/java/com/umbrella/domain/Chat/ChatMessageRepository.java
- src/main/java/com/umbrella/domain/Chat/ChatRoom.java
- src/main/java/com/umbrella/domain/Chat/ChatRoomJoin.java
- src/main/java/com/umbrella/domain/Chat/ChatRoomJoinRepository.java
- src/main/java/com/umbrella/domain/Chat/ChatRoomRepository.java
- src/main/java/com/umbrella/dto/chat/ChatDto.java
- src/main/java/com/umbrella/dto/chat/ChatMessageLogDto.java
- src/main/java/com/umbrella/dto/chat/ChatRoomDto.java
- src/main/java/com/umbrella/dto/chat/ChatRoomsResponseDto.java
- src/main/java/com/umbrella/service/Impl/ChatRoomServiceImpl.java
- src/main/java/com/umbrella/service/Impl/ChatServiceImpl.java
- src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
* Chat 기능 개발
* 아직 미완성 기능이기 때문에 클로즈할 이슈는 없음
> Feat Chat 기능 일부 개발

- src/main/java/com/umbrella/domain/exception/UserExceptionType.java
- src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
- src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
- src/main/java/com/umbrella/service/Impl/CustomOAuth2UserServiceImpl.java
계산했을 때 5세 미만의 생년월일을 입력한 사람은 회원가입이 불가능하도록 만들었음
20230420 등등 말도 안되는 생년월일을 입력하는 것을 방지하는 것이 목적
> [FEAT] UserExceptionType IMPOSSIBLE_AGE_ERROR 추가

- src/main/java/com/umbrella/domain/Post/Post.java
- src/main/java/com/umbrella/dto/post/PostListResponseDto.java
- src/main/java/com/umbrella/dto/post/PostResponseDto.java
- src/main/java/com/umbrella/service/Impl/PostServiceImpl.java
Post Entity field 
viewCount -> likeCount 
Dto field Add likeCount 
PostServiceImpl deleteMethod Add a Heart remove
#37 
#34
> [REFATOR] Change Post Method

- src/main/java/com/umbrella/service/Impl/HeartServiceImpl.java
ExceptionCode REFACTOR
ExceptionCode REFACTOR
#34
> [REFACTOR] ExceptionCode REFACTOR

- src/main/java/com/umbrella/controller/UserController.java
- src/main/java/com/umbrella/domain/exception/PostExceptionType.java
- src/main/java/com/umbrella/domain/exception/UserException.java
- src/main/java/com/umbrella/domain/exception/UserExceptionType.java
- src/main/java/com/umbrella/dto/user/UpdatePasswordDto.java
- src/main/java/com/umbrella/dto/user/UserRequestLoginDto.java
- src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
- src/main/java/com/umbrella/dto/user/UserUpdateDto.java
- src/main/java/com/umbrella/dto/user/WithdrawUserDto.java
- src/main/java/com/umbrella/security/SecurityConfig.java
- src/main/java/com/umbrella/security/login/cookie/CookieOAuth2AuthorizationRequestRepository.java
- src/main/java/com/umbrella/security/login/filter/JsonEmailPasswordAuthenticationFilter.java
- src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
- src/main/java/com/umbrella/security/login/handler/LoginFailureHandler.java
- src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
- src/main/java/com/umbrella/security/login/handler/OAuth2LoginFailureHandler.java
- src/main/java/com/umbrella/security/login/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/umbrella/security/utils/CookieUtil.java
- src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
- src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
- src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
- src/test/java/com/umbrella/project_umbrella/jwt/JwtAuthenticationProcessingFilterTest.java
큰 변경사항은 없고 대부분 코드 중복 제거 및 사용하지 않는 import 삭제 혹은 코드 가독성 상승을 위한 변경임
기존 내용에서 변경이 있었던 부분은 비밀번호와 관련된 부분인데 기존 8자리에서 30자리까지 입력 가능했던 정규식을 8자리에서 20자리까지로 수정함 
추가적으로 UpdatePasswordDto 의 checkPassword 필드에도 정규식을 추가함
> [REFACTOR] warnings 가 나타난 부분들 수정할 수 있는 거 수정함

- src/main/java/com/umbrella/controller/PostController.java
- src/main/java/com/umbrella/domain/Board/BoardRepository.java
- src/main/java/com/umbrella/domain/Post/Post.java
- src/main/java/com/umbrella/dto/post/PostSaveRequestDto.java
- src/main/java/com/umbrella/service/Impl/PostServiceImpl.java
Board Entity 추가로 인한 PostSaveRequestDto 에 boardTitle 필드 추가,
BoardRepository 에 findByTitle() 메서드 추가,
status 코드 전송을 위한 Post Controller REFACTORING 
Board Entity 추가로 인한 PostSaveRequestDto 에 boardTitle 필드 추가,
BoardRepository 에 findByTitle() 메서드 추가,
status 코드 전송을 위한 Post Controller REFACTORING 
Board <-> Post 간의 연관관계 설정 Board 1 : N Post 설정 
save, update, findById, delete, findPosts, searchPost 수정
> [REFACTOR] Board Entity 추가로 인한 Dto 필드 수정, status 코드 전송을 위한 컨트롤러 코드 수정

- src/main/java/com/umbrella/domain/Comment/ChildComment.java
- src/main/java/com/umbrella/domain/Post/Post.java
- src/main/java/com/umbrella/domain/PostImg/PostImg.java
- src/main/java/com/umbrella/service/Impl/ChildCommentServiceImpl.java
* PostImg 엔티티를 제작하였습니다. 
* 부모 테이블인 Post 엔티티가 삭제되었을 경우 바로 관련 엔티티들도 삭제되게끔 @OnDelete 옵션을 사용했습니다.
> [FEAT] : add PostImg Entity

- src/main/java/com/umbrella/controller/UserController.java
- src/main/java/com/umbrella/domain/WorkSpace/WorkSpace.java
- src/main/java/com/umbrella/domain/WorkSpace/WorkspaceUser.java
- src/main/java/com/umbrella/domain/exception/WorkspaceExceptionType.java
- src/main/java/com/umbrella/dto/workspace/EventResponseDto.java
- src/main/java/com/umbrella/dto/workspace/WorkspaceResponseCreateDto.java
- src/main/java/com/umbrella/service/Impl/BoardServiceImpl.java
- src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
- src/main/java/com/umbrella/service/Impl/WhenToMeetServiceImpl.java
- src/main/java/com/umbrella/service/Impl/WorkSpaceServiceImpl.java
WorkspaceResponseCreateDto 추가, Workspace 생성 시 workspace_id 반환함
> [FEAT] Workspace 관련 추가

- src/main/java/com/umbrella/service/Impl/BoardServiceImpl.java
- src/main/java/com/umbrella/service/Impl/WorkSpaceServiceImpl.java
> [FIX] Workspace Validation Logic 에서 발생하던 버그 수정 &  오타 수정

- src/main/java/com/umbrella/domain/Board/Board.java
필드 추가
@GeneratedValue(strategy = GenerationType.AUTO)
필드 추가
@GeneratedValue(strategy = GenerationType.AUTO)
필드 추가
@GeneratedValue(strategy = GenerationType.AUTO)
> [REFACTOR] 기본키 생성전략 추가

- src/main/java/com/umbrella/config/mail/MailConfig.java
- src/main/java/com/umbrella/security/SecurityConfig.java
> [REFACTOR] SecurityConfig 수정, MailConfig 수정

- src/main/java/com/umbrella/controller/UserController.java
만약에 이거 했는데 CORS 에러 안뜨면 Spring Security 에서 @Bean 등록 해뒀던 Cors 가 제대로 동작안하는듯
> [FIX] UserController 에 @CrossOrigin 추가 

- src/main/resources/application.yml
[REFACTOR] : .yml update
[REFACTOR] : .yml update
[REFACTOR] : .yml update
> [REFACTOR] : .yml update
